services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    # Uncomment if not accessible through reverse proxy
    # ports:
      # - 8080:8080  # Web UI
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      VIRTUAL_PORT: 8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - jenkins-net
      - nginx-proxy-net

  agent:
    container_name: jenkins_agent
    image: jenkins/ssh-agent:jdk17
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    restart: unless-stopped
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge
  nginx-proxy-net:
    external: true
